version: "3"
services:
  nginx: # 服务名称，用户自定义
    image: nginx:1.18  # 镜像版本
    ports:
      - 80:80  # 暴露端口
    container_name: nginx
    volumes: # 挂载
      - /usr/local/dockerDir/nginx/html:/usr/share/nginx/html
      - /usr/local/dockerDir/nginx/config/nginx.conf:/etc/nginx/nginx.conf
    privileged: true # 这个必须要，解决nginx的文件调用的权限问题
    read_only: false
  mysql:
    image: mysql:8.0.20
    volumes:
      - /usr/local/dockerDir/mysql/data:/var/lib/mysql:rw
      # 挂载配置文件目录
      - /usr/local/dockerDir/mysql/conf:/etc/mysql/conf.d:rw
      - /usr/local/dockerDir/mysql/logs:/logs:rw
    container_name: mysql
    ports:
      - "3308:3306"
    command:
      - '--default-authentication-plugin=mysql_native_password'
      - '--character-set-server=utf8mb4'
    restart: always
    privileged: true
    environment:
      MYSQL_ROOT_PASSWORD: "&*(erpadmin&*("
      MYSQL_INITDB_SKIP_TZINFO: "Asia/Shanghai"
  redis:
    container_name: redis
    image: redis:5.0.5
    environment:
      - TZ=Asia/Shanghai # 设置时区
    volumes: # 配置数据卷
      - /usr/local/dockerDir/redis:/data
      - /usr/local/dockerDir/redis/config/redis.conf:/etc/redis/redis.conf
    ports: # 映射端口
      - "6379:6379"
    sysctls: # 设置容器中的内核参数
      - net.core.somaxconn=1024
    #  - vm.overcommit_memory=1
    command: /bin/sh -c "echo 'vm.overcommit_memory = 1' >> /etc/sysctl.conf
      && redis-server /etc/redis/redis.conf --appendonly yes
      && redis-server /etc/redis/redis.conf --requirepass JqssWORrauyc" # 指定配置文件并开启持久化
    privileged: true


  server:
    image: laotabu-bg:latest
    build: . # 表示以当前目录下的Dockerfile开始构建镜像
    container_name: laotabu-bg
    ports:
      - 8081:8081
    restart: always
    depends_on: # 依赖与mysql、redis，其实可以不填，默认已经表示可以
      - mysql
      - redis

